### ISSUE TITLE
Object type variables do not display properly on forms

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1355]
**Describe the bug**

Object type variables do not display properly on forms.

**Steps to reproduce**
1. Add a template with source `https://github.com/unitong/test-variable`. The variable `test_object` is defined as follows,

```
variable "test_object" {
  type          = object({
    name        = string
    age         = number
    email       = optional(object({
        address = string
        domain  = string
    }))
  })
  default       = {
    name        = "Bob"
    age         = 23
    email       = {
        address = "bob"
        domain  = "example.com"
    }
  }
}
```

**Result**

1. Properties in the object are displayed directly on the form and it is not clear which field they belong to. And the default values are not displayed.
<img width="2515" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/722c2b69-54a9-468f-90e7-350719c360c3">

2. Checked the schema.
```
        test_object:
          default:
            age: 23
            email:
              address: bob
              domain: example.com
            name: Bob
          properties:
            age:
              title: age
              type: number
            email:
              properties:
                address:
                  title: address
                  type: string
                domain:
                  title: domain
                  type: string
              required:
                - address
                - domain
              title: email
              type: object
            name:
              title: name
              type: string
          required:
            - age
            - name
          title: test_object
          type: object
```

**Expected behavior**

1. User can find the `test_object` field and clearly see the structure of the object type variables.

**Environment**
- Walrus version: main 6d4903951fc8b6284473bfbae8fe8f0fea34ecd4
- UI version: dev-d45e562

**Additional context**
