### ISSUE TITLE
enum does not  in certain cases

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1476]
d**Describe the bug**

enum does not  in certain cases

**Steps to reproduce**
1. Add a template with source `https://github.com/walrus-catalog-sandbox/terraform-kubernetes-redis?ref=main`
2. Enable the template for service.
3. New a service using the template above.
4. Select `replication` in `Architecture` field.
5. Check the `Replication Readonly Replicas` field.
```
replication_readonly_replicas:
          default: 1
          description: >
            Specify the number of read-only replicas under the replication
            deployment.
          enum:
            - 1
            - 3
            - 5
          title: Replication Readonly Replicas
          type: number
          x-walrus-ui:
            group: Basic
            order: 4
            showIf: architecture=replication
```

**Result**

1. The enum did not take effect.
<img width="2510" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/35fefccc-185d-4d60-bc77-6348a367e798">

**Expected behavior**

**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-e4baff9

**Additional context**
