### ISSUE TITLE
Show empty group when all properties are hidden

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1485]
**Describe the bug**

**Steps to reproduce**
1. Go to `deploy-source-code` template detail page.
2. Check the UI schema preview.

**Result**

1. There is an empty `Basic` group.
<img width="897" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f9ab6055-519a-470e-b8e5-26e5163e1a68">

2. Check the UI schema. The property of basic group is hidden.
```
components:
  schemas:
    variables:
      properties:
        context:
          additionalProperties:
            type: object
          default: {}
          description: >
            Receive contextual information. When Walrus deploys, Walrus will
            inject specific contextual information into this field.


            Examples:

            ```

            context:
              project:
                name: string
                id: string
              environment:
                name: string
                id: string
              resource:
                name: string
                id: string
            ```
          title: Context
          type: object
          x-walrus-ui:
            colSpan: 12
            group: Basic
            hidden: true
            order: 23
```
**Expected behavior**

Do not show the group if all properties are hidden.

**Environment**
- Walrus version: f94d57de903a925f2bd72d34b5aa1eaf8213f6ad
- UI version: dev-ab43587

**Additional context**
