### ISSUE TITLE
Prettify CLI json output

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1531]
It's missing indentation.
<img width="439" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/70208b04-af9c-4f3f-93d7-07418ae0a0a8">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 387b458b939852736bdcc40f2f83fec184da6b3f
- UI version: dev-4478a77

1. Create a service using `kubernetes-containerservice` template.
2. Execute cli command `walrus resource get-outputs <service-name>`

**Test Result:** 
Need better readability.
<img width="1669" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/6f1aa683-0b63-42e8-9433-8f151daad40f">

**Comment by Finenyaco** [comment]
**Test Result:** Failed

```
clientVersion:
  version: main
  gitCommit: 0a3779654c43dfb1a5d3299c4862502a909f2878
serverVersion:
  version: main
  gitCommit: 0a3779654c43dfb1a5d3299c4862502a909f2878
```

The formatting is incomplete.

<img width="718" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/0ba1ffc3-3867-4d91-8ed5-f6058792ed99">

<img width="625" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/3fb192b3-d77c-47e5-ae72-551793c0f115">
