### ISSUE TITLE
schema rendering does not work as expected

### ISSUE THREAD

**Issue by aiwantaozi** [seal-io/walrus#1552]
**Describe the bug**
schema rendering doesn't work as expected 

## Steps to reproduce
1. Import https://github.com/michelia-io/test-terraform-variable?ref=simple
2. Check the rendering UI

### Case 1
**Result**
<img width="1828" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/b1b4199d-14af-4c43-b45f-1ce54f348d12">
map bool field does not work as expected.

```yaml
map_bool:
          additionalProperties:
            type: boolean
          default:
            isNow: true
          nullable: true
          title: Map Bool
          type: object
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 25
```

### Case 2

<img width="1818" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/03626132-d71f-4b15-ba08-caf3e16d02b7">

```yaml
list_list_str:
          default:
            - - a1
          items:
            items:
              type: string
            type: array
            x-walrus-ui:
              colSpan: 12
          nullable: true
          title: List List Str
          type: array
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 11
```

### Case 3
<img width="1824" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/78807ed0-fa87-4928-9328-7032d3dbc3b1">

```yaml
list_map_string:
          default:
            - name: default-node-pool
          description: List of maps containing node pools
          items:
            additionalProperties:
              type: string
            type: object
            x-walrus-ui:
              colSpan: 12
          nullable: true
          title: List Map String
          type: array
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 12
```

### Case 4
<img width="1823" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/4488c2c4-22de-424d-821e-d16c0081616a">

```yaml
list_map_any:
          default:
            - name: default-node-pool
          description: List of maps containing node pools
          items:
            additionalProperties:
              type: object
              x-walrus-ui:
                colSpan: 12
            type: object
            x-walrus-ui:
              colSpan: 12
          nullable: true
          title: List Map Any
          type: array
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 13
```

**Environment**
- Walrus version:
v0.4.0-rc3

**Additional context**
