### ISSUE TITLE
external doc config in schema not work

### ISSUE THREAD

**Issue by aiwantaozi** [seal-io/walrus#1600]
**Describe the bug**
```yaml
properties: 
  outbound_ipv6_traffic:
    title: outbound IPv6 traffic
    type: string
    externalDocs:
      description: Read More
      url: https://docs.aws.amazon.com/lambda/latest/dg/configuration-vpc.html
```

**Steps to reproduce**
1. Customize the schema, add externalDocs config
2. check the UI render, externalDocs config does not show

**Result**

**Expected behavior**
externalDocs config should add a clickable "Read More" link to the description.

**Environment**
- Walrus version:
UIdev-17c83b3

**Additional context**
