### ISSUE TITLE
The readOnly option for schema doesn't work

### ISSUE THREAD

**Issue by aiwantaozi** [seal-io/walrus#1601]
**Describe the bug**

**Steps to reproduce**
1. update schema for webservice, config readOnly
```yaml
image:
          default: nginx
          description: Docker image name
          readOnly: true
          title: Image Name
          type: string
          x-walrus-ui:
            group: Basic
            immutable: true
            order: 1
```

2. create the service with webservice

Check the UI, the image is editable

<img width="788" alt="image" src="https://github.com/seal-io/walrus/assets/5936271/2e2c9803-7593-494c-8a5f-e50c720b267e">

**Result**
the readOnly configuration for schema does not work

**Expected behavior**
the readOnly should not be editable

**Environment**
- Walrus version:
v0.4.0-rc3

**Additional context**
