### ISSUE TITLE
Incorrect values submitted for complex type variables

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1653]
**Describe the bug**

Incorrect values submitted for complex type variables

**Steps to reproduce**
1. Add a template with source `https://github.com/michelia-io/test-terraform-variable?ref=simple`.
2. Create a service using the template above. The configuration is shown below:

<img width="2446" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/c93a4ad4-2c44-487d-8e2e-3fdbec99477c">

<img width="745" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/541170a4-6dc9-48b4-8f6c-7593efb822e7">

3. Check the deployment result.

**Result**

1. Failed to deploy. Check the errors from deployment logs.
<img width="1048" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/98525169-a52a-4e01-ac4c-e85d14256dfd">

```
Error: Invalid value for input variable

  on main.tf line 17, in module "test-var":
  17:   list_list_str = [[["test", "1", "12"]], [["dds", "sdfa"]]]

The given value is not suitable for module.test-var.var.list_list_str
declared at .terraform/modules/test-var/main.tf:8,1-25: element 0: element 0:
string required.

Error: Invalid value for input variable

  on main.tf line 18, in module "test-var":
  18:   list_map_string = [{
  19:     "0" = {
  20:       test  = "123"
  21:       test2 = "456"
  22:     }
  23:     name = "default-node-pool"
  24:     }, [{
  25:       test3 = "123"
  26:   }]]

The given value is not suitable for module.test-var.var.list_map_string
declared at .terraform/modules/test-var/main.tf:13,1-27: element 0: element
"0": string required.
```
2. Check the main.tf
```
module "test-var" {
  list_list_str = [[["test", "1", "12"]], [["dds", "sdfa"]]]
  list_map_string = [{
    "0" = {
      test  = "123"
      test2 = "456"
    }
    name = "default-node-pool"
    }, [{
      test3 = "123"
  }]]
  map_bool = {
    isNow      = true
    test-false = false
    test-true  = true
  }
```

**Expected behavior**

Submit the correct values.

**Environment**
- Walrus version: v0.4.0
- UI version: dev-16fdf3c

**Additional context**

It didn't show the default value as well.
<img width="2514" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/86a9ce14-7e34-4249-a18e-4892f66dc987">

```
list_list_str:
          default:
            - - a1
          items:
            items:
              type: string
            type: array
            x-walrus-ui:
              colSpan: 12
          nullable: true
          title: List List Str
          type: array
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 2
```
