### ISSUE TITLE
Incorrect default values for array type properties

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1685]
**Describe the bug**

**Steps to reproduce**
1. New a resource definitions.
2. Add a rule with `kubernetes-containerservice` template.
3. Configure `Execute` field as shown below:

<img width="791" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/26d06981-38ab-4e48-80b5-8077f49058a3">

4. Check the UI schema of the resource definitions.

**Result**

1. The default value for array type properties is incorrect.
<img width="785" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/1ff6be08-9ad4-49ea-82d4-c551343bb070">

<img width="849" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/9f290735-48ff-4862-89e2-4c6c19f3f853">

<img width="1071" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/aa811ce0-769c-4303-ac71-08c61cb5c703">

**Expected behavior**

Display the correct defaults.

**Environment**
- Walrus version: main ab30b62917ad1ab35c43d37fb7a646efbd9a1572
- UI version: dev-2d14c4a

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main ab30b62917ad1ab35c43d37fb7a646efbd9a1572
- UI version: dev-2d14c4a

**Test Result:**

1. Add two ports as follows:
<img width="781" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/817a8aac-ed71-4777-b2e8-5b55f7744405">

2. It dose not show the values until click on `+`.
<img width="805" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/6987b6c8-b1aa-4bb6-963f-b84bc374a196">

<img width="826" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/44d8c072-8ade-4d29-859a-8f70c7f46fb2">

3. Check the UI schema.

<img width="772" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/1175dd3c-f66f-4d9b-bf03-6c5297a816a8">

4. The default value of ports should be :
```
...
ports:
    default: 
        - external: 80
           internal: 80
           protocol: tcp
        - external: 8080
           internal: 8080
           protocol: tcp
    description: |
         Configure the ports.
    items:
         properties:
              ...
```

**Comment by Finenyaco** [comment]
It does not save the default values for any type variables.

**Test Steps:** 
1. Add a template with source `https://github.com/terraform-aws-modules/terraform-aws-app-runner`.
2. New a resource definition and add a rule with the template above.
3. Configure the `Health Check Configuration` field.
4. Go to resource definition details page and check the UI schema.

**Test Results:**
1. No defaults.
<img width="764" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/61f1771e-85f9-4e47-bb7d-8d6059d85ad6">

```
health_check_configuration:
          default: {}
          description: The health check configuration for the service
          nullable: true
          title: Health Check Configuration
          type: object
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 7
```

**Environment**
- Walrus version: main 387b458b939852736bdcc40f2f83fec184da6b3f
- UI version: dev-4c1bb33
