### ISSUE TITLE
Default values for template/resource definitions not fully in effect

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1773]
**Describe the bug**

**Steps to reproduce**
1.  Go to template page and add a default value to `Ports` of template `kubernetes-containerservice` as bellows:
<img width="2467" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/b90c3640-2d09-4ec3-9883-a684868eca0d">

2. Create a resource using template `kubernetes-containerservice`.
<img width="2416" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/bff4bed0-f607-48fe-afff-91cd17e3f800">

3. Check deployed resources on the k8s cluster.

**Result**

1. Check the service, external port didn't work.

```
 ~/seal/cli_yaml/ k get all -n default-orb-dev
NAME                                         READY   STATUS             RESTARTS       AGE
pod/test-nginx-xb9sx-58957b8b65-4488g        1/1     Running            0              2m21s


NAME                                     TYPE        CLUSTER-IP        EXTERNAL-IP   PORT(S)          AGE
service/test-nginx                       ClusterIP   None              <none>        <none>           2m21s            <<<<

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/test-nginx-xb9sx         1/1     1            1           2m21s


NAME                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/test-nginx-xb9sx-58957b8b65        1         1         1       2m21s
```
2. Checked the template configuration in resource details page. The external port became empty.
<img width="2550" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/195b2ce9-ec54-49eb-bf53-50b907944be8">

3. Checked the resource quota. `resources` was empty, not the default value.
```
spec:
  automountServiceAccountToken: false
  containers:
  - env:
     ...
    image: nginx
    imagePullPolicy: IfNotPresent
    name: run-0-nginx
    ports:
    - containerPort: 80
      name: tcp-80
      protocol: TCP
    resources: {}             <<<
    securityContext:
      allowPrivilegeEscalation: true
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
```
**Expected behavior**

Deploy resource using default values.

**Environment**
- Walrus version: main c7fc65ae3ea5546452dd515722f9f0c0712c3e15
- UI version: dev-290afb6

**Additional context**
