### ISSUE TITLE
 Enhance the command for switching environments

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1782]
**Is your enhancement related to a problem? Please describe.**

Currently, using `walrus config setup -e <env-name>` to switch environments by CLI.   For users unfamiliar with the product, this may not be easily discovered.

**Describe the solution you'd like**

Make the command for switching environments more intuitive and understandable.

**Describe alternatives you've considered**

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
```
clientVersion:
  version: main
  gitCommit: 7428401fef1d1a45e433c2e7722597a5e12830ef
  isDevVersion: true
serverVersion:
  version: main
  gitCommit: 7428401fef1d1a45e433c2e7722597a5e12830ef
  isDevVersion: true
```

**Test Result:**

I think it would be better to automatically print the current context after switching the project/environment. e.g.

```
 ~/seal/ walrus context switch -p default -e local
Current Project: default
Current Environment: local
```
