### ISSUE TITLE
Successfully create a resource without template but fail to upgrade

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1783]
**Describe the bug**

**Steps to reproduce**
1. Create a resource without template via walrus file.

```
version: v1
resources:
- name: test-nginx
  attributes:
    containers:
    - image: nginx
      ports:
      - external: 80
        internal: 80
```
2. Upgrade the resource after adding the template information as below:
```
version: v1
resources:
- name: test-nginx
  template:
    name: kubernetes-containerservice
    version: v0.1.3
  attributes:
    containers:
    - image: nginx
      ports:
      - external: 80
        internal: 80
```

**Result**

1. Created a resource without template successfully.
<img width="2262" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/1e7acb4a-a539-4282-b09e-c93345ce689c">

2. Failed to upgrade.
```
resource default/orb-dev/test-nginx apply failed
unexpected status code 400, {"message":"template or resource definition is required","status":400,"statusText":"Bad Request"}
```

**Expected behavior**

**Environment**
- Walrus version: c7fc65ae3ea5546452dd515722f9f0c0712c3e15

**Additional context**
