### ISSUE TITLE
fail to apply walrus file

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1797]
**Steps to reproduce**
1. Import the following yaml
```
resources:
- name: nginx
  template:
    name: kubernetes-containerservice
    version: v0.1.3
  attributes:
    containers:
    - image: nginx
      ports:
      - internal: 80
        external: 80
```

**Result**
<img width="802" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/1dccfec9-03aa-4cb2-844b-992c076bfa1a">

**Environment**
- Walrus version: dev-babd256
