### ISSUE TITLE
 When executing scheduled tasks, the operator for the revision is incorrect

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1870]
**Describe the bug**

**Steps to reproduce**
1. Create two resources using the walrus fie as below:
```
resources:
- name: nginx-1
  template:
    name: kubernetes-containerservice
    version: v0.2.3
  attributes:
    containers:
    - image: nginx
      ports:
      - internal: 80
        external: 80
- name: nginx-2
  template:
    name: kubernetes-containerservice
    version: v0.2.3
  attributes:
    containers:
    - image: nginx
      ports:
      - internal: 80
        external: 80
      envs:
      - name: nginx-address
        value: ${res.nginx-1.address}
```
2. Create user called `test` and add it as default project member with 'member' role.
3. Login walrus as `test` user.
4. Stop these two resources in batch and check the revision.
5. Start the two resources in batch and check the revision.

**Result**

1. The operator is wrong for nginx-1 when stop.
<img width="2546" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f9b4930b-0a1a-4c32-b8b4-de4564fca5d8">

2. The operator is wrong for nginx-2 when start.
<img width="2560" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/d95b4159-b2e8-44c4-8037-f8518477eeed">

**Expected behavior**

**Environment**
- Walrus version: main 645047fbb578508e9b8ab46353195be7de52f22e
- UI version: dev-6762e0b

**Additional context**
