### ISSUE TITLE
Import yaml fails if the attributes field is not present

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1923]
Import the following yaml fails:
```
resources:
  - name: test
    type: postgresql
```

Import the following yaml succeeds:
```
resources:
  - name: test
    type: postgresql
    attributes: {}
```

**Environment**
- Walrus version: main
