### ISSUE TITLE
Provide a Walrus file for Walrus

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1928]
Add a walrus file in https://github.com/seal-io/walrus/tree/main/deploy/manifests

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 98e5445080de1e1017db16951dd12d8e1e52b27f
- UI version: dev-3fcbabe

**Test Result:**

In the Walrus file, the `profile` must be configured. Otherwise, the configured ports cannot be viewed on the UI.

<img width="2560" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/e48b3836-a55d-42a2-afac-6fb8c8f2494e">

```
resources:
  - name: walrus-casdoor
    type: containerservice
    attributes:
      containers:
        - image: sealio/casdoor:v1.344.0-seal.1
          profile: run             <<<<
          ports:
            - internal: 8000
              external: 8000
 - name: walrus
    type: containerservice
    attributes:
      containers:
        - image: sealio/walrus:main
          profile: run             <<<<
          ports:
            - internal: 80
              external: 80
            - internal: 443
              external: 443
```
