### ISSUE TITLE
Deploying resources with the same name and different types through walrus file will not return an error

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1935]
**Describe the bug**

Deploying resources with the same name and different types through walrus file will not return an error

**Steps to reproduce**
1. Create a resource by walrus file as below:

```
resources:
  - name: db
    type: mysql
    attributes: {}
```

2. Create another resource with the same name, but the type is different.
```
version: v1
resources:
- name: db
  type: postgresql
  attributes:
    resources:
      cpu: 0.2
      memory: 1024
```

**Result**

1. The created resource has been upgraded, and the parameters have been modified. The default value for cpu is 0.25.
<img width="2388" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/a24c5dad-9b48-4db4-b800-bc5330a4b5e8">

**Expected behavior**

1. Prompt that type/template is different and no upgrade will be performed.

**Environment**
- Walrus version: main a12b753f2e823aa7a7456110215dceed4da46ba1
- UI version: dev-07fa8db

**Additional context**
