### ISSUE TITLE
Failed create resources after adding default values in UI schema: invalid variables: violate ui schema

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1950]
**Describe the bug**

**Steps to reproduce**
1. Edit template `kubernets-containerservice` and add a default value for `Envs`.
```
envs:
    default:
      - name: test
        value: 123
...
```
2. Create a resource using template `kubernetes-containerservice`.
3. Check the deployment result.

**Result**

1. Failed to create resource: `invalid variables: violate ui schema: invalid containers: value must be a string`.
<img width="1673" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/f262b7c5-535a-4b57-a6e8-d5dfcfb6f8c0">

2. Continuously click "Save" quickly. It can be created successfully.
<img width="1581" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/a9c18685-688d-436b-a3b2-5913f06f814c">

**Expected behavior**

**Environment**
- Walrus version: main 66f1bd1681cc926d6b35a6caed7ec5f793ae103a
- UI version: dev-21d34af

**Additional context**

**Comment by thxCode** [comment]
@Finenyaco try as below
```
envs:
    default:
      - name: test
        value: "123"
```

generally, YAML is not type-sensitive, it tries to guess, if you want a number to be a string, quote it.
