### ISSUE TITLE
Resource stuck in deleting state

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1953]
**Describe the bug**

Resource stuck in Deleting state

**Steps to reproduce**
1. Create resource 'a'.
```
version: v1
resources:
- name: a
  template:
    name: kubernetes-containerservice
    version: v0.2.5
  attributes:
    containers:
    - image: nginx
      profile: run
    deployment:
      rolling:
        max_surge: 0.25
        max_unavailable: 0.25
      timeout: 300
      replicas: 1

```

2. Delete resource 'a' and create resource 'b' immediately. 
```
version: v1
resources:
- name: b
  template:
    name: kubernetes-containerservice
    version: v0.2.5
  attributes:
    containers:
    - envs:
      - name: a
        value: ${res.a.connection}
      image: nginx
      profile: run
    deployment:
      rolling:
        max_surge: 0.25
        max_unavailable: 0.25
      timeout: 300
      replicas: 1
```

**Result**

1. Resource 'a' stuck in deleting state.
<img width="2452" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/6773e325-ea50-4338-957e-88f79c96e2a3">

**Expected behavior**

**Environment**
- Walrus version: main 66f1bd1681cc926d6b35a6caed7ec5f793ae103a
- UI version: dev-21d34af

**Additional context**
