### ISSUE TITLE
cli prints a warning message on list commands

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1959]
<img width="1022" alt="image" src="https://github.com/seal-io/walrus/assets/5697937/98cd20c9-a4c1-43cb-999a-a99a2187e1b3">

**Environment**
```
clientVersion:
  version: dev
  gitCommit: 9a4516ef8771ed0bdce4acb990f084aa4e9a2a11
  isDevVersion: true
```

**Comment by Finenyaco** [comment]
**Environment**
```
clientVersion:
  version: main
  gitCommit: 4eef11db3efc80ce93bb17814e5e8fb822d75d45
  isDevVersion: true
serverVersion:
  version: main
  gitCommit: 4eef11db3efc80ce93bb17814e5e8fb822d75d45
  isDevVersion: true
```

**Test Result:** pass
```
 ~/ w variable list
 ID                   NAME               VALUE         CREATED
-------------------- ------------------ ------------- -----------------------------
 497531122612204802   project-password   <sensitive>   2024-01-24T07:27:38.284776Z
 ~/ w project list
 ID                   NAME      CREATED
-------------------- --------- ----------------------------
 497517331371554050   default   2024-01-24T05:10:38.06008Z
 ~/ w environment list
 ID                   NAME    TYPE          CREATED
-------------------- ------- ------------- -----------------------------
 497517331371554050   local   development   2024-01-24T05:10:38.064002Z
```
