### ISSUE TITLE
Restarting Walrus through docker-compose, Walrus startup failure

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1991]
**Describe the bug**

**Steps to reproduce**
1. Run Walrus server by docker compose.
```
version: '3.6'
services:
  seal:
    image: "sealio/walrus:main"
    restart: always
    privileged: true
    container_name: seal
    command:
      - "walrus"
      - "--log-debug"
      - "--log-verbosity=5"
    environment:
      - K3S_RESOLV_CONF=
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - 'walrus-app:/var/run/walrus'
volumes:
  walrus-app: {}
```
2. Execute `docker-compose down`.
3. Execute `docker-compose up`.
4. Check the running status of Walrus server.

**Result**

1. Walrus failed to startup.
```
2024-01-22T10:03:55.007Z	I	k3s	time="2024-01-22T10:03:55Z" level=fatal msg="flannel exited: failed to acquire lease: subnet \"192.168.109.0/24\" specified in the flannel net config doesn't contain \"192.168.169.0/24\" PodCIDR of the \"local\" node"
2024-01-22T10:03:55.026Z	I	signal.handler	received signal "child exited"
2024-01-22T10:03:55.026Z	I	signal.handler	reaped child process 47
2024-01-22T10:03:55.026Z	E	error running embedded kubernetes: exit status 1
github.com/seal-io/walrus/utils/log.DelegatedLogger.Errorf
	github.com/seal-io/walrus/utils@v0.0.0-00010101000000-000000000000/log/delegate.go:168
github.com/seal-io/walrus/utils/log.Errorf
	github.com/seal-io/walrus/utils@v0.0.0-00010101000000-000000000000/log/logger.go:174
github.com/seal-io/walrus/pkg/server.(*Server).Run.func1
	github.com/seal-io/walrus/pkg/server/runner.go:525
github.com/seal-io/walrus/utils/gopool.contextWaitGroup.Go.func1
	github.com/seal-io/walrus/utils@v0.0.0-00010101000000-000000000000/gopool/waitgroup.go:115
github.com/alitto/pond.(*TaskGroupWithContext).Submit.func1
	github.com/alitto/pond@v1.8.3/group.go:60
github.com/alitto/pond.(*WorkerPool).executeTask
	github.com/alitto/pond@v1.8.3/pond.go:454
github.com/alitto/pond.worker
	github.com/alitto/pond@v1.8.3/worker.go:32
2024-01-22T10:03:55.027Z	F	error getting embedded casdor: dial tcp4 127.0.0.1:8000: connect: connection refused
github.com/seal-io/walrus/utils/log.DelegatedLogger.Fatal
	github.com/seal-io/walrus/utils@v0.0.0-00010101000000-000000000000/log/delegate.go:136
github.com/seal-io/walrus/utils/log.Fatal
	github.com/seal-io/walrus/utils@v0.0.0-00010101000000-000000000000/log/logger.go:154
main.main
	github.com/seal-io/walrus/cmd/server/server.go:17
runtime.main
	runtime/proc.go:267

```

**Expected behavior**

**Environment**
- Walrus version: main b078bbf3a6cd394d94c0511c2d5b5a86a269c748
- UI version: dev-f8b27a1

**Additional context**
Walrus successfully restarted executing `docker-compose restart`.
