### ISSUE TITLE
default-local namespace will be deleted after restarting Walrus

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#2014]
**Describe the bug**

**Steps to reproduce**
1. Run Walrus by docker compose.
```
version: '3.6'
services:
  seal:
    image: "sealio/walrus:main"
    restart: always
    privileged: true
    container_name: seal
    command:
      - "walrus"
      - "--log-debug"
      - "--log-verbosity=4"
    environment:
      - K3S_RESOLV_CONF=
    ports:
      - "80:80"
      - "443:443"
      - "54322:5432"
    volumes:
      - 'walrus-app:/var/run/walrus'
volumes:
  walrus-app: {}
```

2. Create several resources in the default-local environment.
3. Execute `docker-compose down`.
4. Execute `docker-compose up`.
5. Redeploy to resources.

**Result**

1. Failed to redeploy. The "default-local" namespace was deleted.

<img width="854" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/688545ad-dd83-46e9-9c1c-9bd16343c735">

**Expected behavior**

Redeploy resource successfully.

Can we retain this namespace? Or automatically recreate the namespace upon restarting Wlarus.

**Environment**
- Walrus version: main 4eef11db3efc80ce93bb17814e5e8fb822d75d45
- UI version: dev-94aee09

**Additional context**
