### ISSUE TITLE
When using 'showIf' in variables configured with the YamlEditor widget, the functionality is not correct

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#2027]
**Describe the bug**

When using 'showIf' in variables configured with the YamlEdit widget, the functionality is not correct

**Steps to reproduce**
1. Add a template with source `https://github.com/unitong/test-upgrade?ref=main`.
2. Add a 'showIf' extension to 'map_may' variable in UI schema:
```
map_any:
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          default: {}
          externalDocs:
            description: User Guide
            url: https://seal-io.github.io/docs/
          title: Map Any
          type: object
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 6
            showIf: test_bool=true
            widget: YamlEditor
```
3 Click on the preview button on the UI Schema page.
4. Enable 'test_bool' and then disable it.

**Test Result:**

1. When ‘test_bool’ is disabled, the ‘test_str’ variable is also hidden.

https://github.com/seal-io/walrus/assets/26084756/49b7287e-3ec1-4d50-bb02-1eb1e775f0dd

2. Check the UI schema.
<img width="1056" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/9dce4712-508a-421e-89eb-d3e0577e59c2">

**Expected behavior**

1. Should not hide the 'test_str' variable.

**Environment**
- Walrus version: v0.5.0-rc3

**Additional context**
