### ISSUE TITLE
Hide unnecessary commands in the Walrus CLI

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#2042]
**Describe the bug**

Some CLI commands are not needed, please hide them.

e.g.
- walrus resourcecomponent get-keys
- walrus resourcecomponent exec 
- walrus resourcecomponent log

```
root@ip-192-168-1-125:~# walrus resourcecomponent -h
Usage:
  walrus resourcecomponent [command]

Available Commands:
  exec        Exec for a resource component.
  get-keys    Get keys for a resource component.
  list        Get resource components.
  log         Log for a resource component.

Global Flags:
  -d, --debug   Enable debug log
  -h, --help    Help for this command

Use "walrus resourcecomponent [command] --help" for more information about a command.
```

**Expected behavior**

**Environment**
- Walrus version: v0.5.0-rc3

**Additional context**

**Comment by Finenyaco** [comment]
**Environment:**
```
clientVersion:
  version: main
  gitCommit: 44305cd5fb89716a1e183344072ec5f805819605
  isDevVersion: true
serverVersion:
  version: main
  gitCommit: 44305cd5fb89716a1e183344072ec5f805819605
  isDevVersion: true
```

```
 ~/ w resourcecomponent -h
Usage:
  walrus resourcecomponent [command]

Available Commands:
  list        Get resource components.

Global Flags:
  -d, --debug   Enable debug log
  -h, --help    Help for this command

Use "walrus resourcecomponent [command] --help" for more information about a command.
```
