### ISSUE TITLE
Re-apply the same Walrus file without modification triggered resource patch

### ISSUE THREAD

**Issue by pengjiang80** [seal-io/walrus#2055]
**Describe the bug**
Re-apply the same Walrus file without modification triggered resource patch

**Steps to reproduce**
1. Start a walrus server with single docker installation
2. Download walrus cli, generate token and config the cli.
3. Save the wordpress walrus file from walrus file hub as app.yaml. The content is as below:
```
resources:
  - name: wordpress-db
    type: mysql
    attributes: {}
  - name: wordpress
    type: containerservice
    attributes:
      containers:
        - image: wordpress
          profile: run
          ports:
            - internal: 80
              external: 80
          envs:
            - name: WORDPRESS_DB_HOST
              value: ${res.wordpress-db.address}
            - name: WORDPRESS_DB_PASSWORD
              value: ${res.wordpress-db.password}
            - name: WORDPRESS_DB_USER
              value: ${res.wordpress-db.username}
            - name: WORDPRESS_DB_NAME
              value: ${res.wordpress-db.database}
```
5. Run "walrus apply -f app.yaml", wait for the deployment to complete.
6. Run "walrus apply -f app.yaml" again without any modification. It will return:
resource default/dev/wordpress unchanged
resource default/dev/wordpress-db patched
7. Re-run "walrus apply -f app.yaml" again without any modification. It will return:
resource default/dev/wordpress unchanged
resource default/dev/wordpress-db patched
8. Check the wordpress-db resource through Walrus UI, it has revisions triggered in 2nd and 3rd apply although the walrus file is the same.
9. Check change history, the 2nd change showed a resource id was added and the 3rd change showed "no modification"

**Environment**
- Walrus version: v0.5.0-rc4
