### ISSUE TITLE
Remove isDevVersion in cli version output

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#2073]
**Steps to reproduce**
1. Download Walrus cli
2. Run `walrus version`

**Result**
```
clientVersion:
  version: v0.5.0
  gitCommit: 44305cd5fb89716a1e183344072ec5f805819605
  isDevVersion: false
```

**Expected behavior**
Do not print isDevVersion

**Comment by Finenyaco** [comment]
**Test Result:** Pass

```
root@ip-192-168-1-125:~# walrus version
clientVersion:
  version: main
  gitCommit: 3b93fab7fcdac5c5ba61984ee7431021a7593592
serverVersion:
  version: main
  gitCommit: e92cde6256262c9671c9d51475f0bee8669f6628
```
