### ISSUE TITLE
Add validation when importing an incomplete YAML file prompts to create resources

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#2256]
**Describe the bug**

Importing an incomplete YAML file prompts successful creation

**Steps to reproduce**
1. Import a yaml file to create a resource as shown below:

```
attributes:
    containers:
    - image: nginx
      envs:
      - name: test
        value: ${res.res-c.address}
```

**Result**

https://github.com/seal-io/walrus/assets/26084756/604986ef-f402-4976-b611-6d1fe02050b1

**Expected behavior**

**Environment**
- Walrus version: v0.6.0-rc2

**Additional context**
