### ISSUE TITLE
Secret values are wrong in app deployment

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#376]
Version: v0.1.0-rc2

Steps:
1. Add a global secret name `abc`, value `abcabc`
2. Add a global secret name `def`, value `defdef`
3. Add a nginx webservice app, set env to:
{
  "abc": "${secret.abc}",
  "def": "${secret.def}"
}
4. Deploy

Result:
```
  containers:
  - env:
    - name: abc
      value: defdef
    - name: def
      value: defdef
```
