### ISSUE TITLE
Resource status is not updated when error happens

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#587]
**Version:** main	
**UI:** dev-d162b1c
**Commit ID:** c8f0bfdfde962e9b74e38e00e4458279d67a2c9e
**Env:** Ubuntu 22.04 amd64

**Test Steps:**
1. Deploy an instance using webservice module.
2. Save the yaml configuration file of deployment.
```
kubectl get deployment.apps/wordpress -n sealtest-web-ins2 -oyaml > deployment.yaml
```
3. Modify the yaml file to make pod initialize failed.
```
    spec:
      automountServiceAccountToken: true
      containers:
      - image: wordpress
        imagePullPolicy: IfNotPresent
        name: wordpress
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      initContainers:                            <--
      - name: init-myservice                     <--
        image: testdf                            <--
```
4. Delete the deployment.
```
kubectl delete deployment.apps/wordpress -n sealtest-web-ins2
```
5. Apply the deployment.
```
kubectl apply -f deployment.yaml
```
6. Wait for the task.resource-status-sync to execute.
7. View the resource status on the seal website.

**Test Result:** 
1. In step7, the status of deployment and pod has not been updated.
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/26084756/236598858-883c9747-2c59-4893-b721-19015d1b5ae3.png">

2. View resource on cluster.
```
root@ip-192-168-1-138:~# kubectl get all -n sealtest-web-ins2
NAME                             READY   STATUS                  RESTARTS       AGE
pod/nginx-5c9998bbd-vnl9d        1/1     Running                 1 (164m ago)   17h
pod/mysql-mysql-0                1/1     Running                 2 (132m ago)   17h
pod/wordpress-67465698d5-vcwjv   0/1     Init:ImagePullBackOff   0              32m

NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
service/mysql-mysql-headless   ClusterIP   None            <none>        3306/TCP       17h
service/mysql-mysql            ClusterIP   10.43.49.170    <none>        3306/TCP       17h
service/nginx                  NodePort    10.43.156.15    <none>        80:30313/TCP   17h
service/wordpress              NodePort    10.43.207.147   <none>        80:30933/TCP   17h

NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nginx       1/1     1            1           17h
deployment.apps/wordpress   0/1     1            0           37m

NAME                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/nginx-5c9998bbd        1         1         1       17h
replicaset.apps/wordpress-67465698d5   1         1         0       32m
```
