### ISSUE TITLE
Instance revision stuck in running state if the job fails to pull image 

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#649]
**Version:** main	
**UI:** dev-1a87bd6
**Commit ID:** 115598ec6675a9d65936b159eaefb199df5e8d5d
**Env:** Ubuntu 22.04 amd64, aws EC2

**Test Steps:**

1. Select a revision and modify the status to `Running`.

<img width="616" alt="image" src="https://github.com/seal-io/seal/assets/26084756/c309b491-3879-4f80-a3bc-677b09902e74">

2. Create a job yaml file `my-job.yaml`, and modify the `seal.io/application-revision-id` to the id of the revision in step 1.

```
apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  labels:
    seal.io/application-revision-id: "459992795550056450"
  namespace: "seal-system"
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: alpine
          image: alpddd:3.6
          command: ["/bin/sh", "-c", "echo Hello Kubernetes! && sleep 1"]
      restartPolicy: Never
```
3. Deploy the job on the embedded Kubernetes of seal. `kubectl apply -f my-job.yaml`.
4. Wait for a while and view the revision status.

**Test Result:** 

1. The revision stuck in running state.
<img width="1008" alt="image" src="https://github.com/seal-io/seal/assets/26084756/2256ede9-5ff5-4ed9-8a0f-88b811b58ab0">
<img width="912" alt="image" src="https://github.com/seal-io/seal/assets/26084756/0943dd3b-5510-465f-a3ff-8f26d55658d8">
